### ISSUE TITLE
MageCLI .Validate(Manifest manifest) object reference not set

### ISSUE THREAD

**Issue by plutext** [dotnet/deployment-tools#313]
```
 Object reference not set to an instance of an object.
3>     at Microsoft.Deployment.MageCLI.Command.Validate(Manifest manifest) in C:\Users\jh\deployment-tools\src\clickonce\MageCLI\Command.cs:line 1639
3>     at Microsoft.Deployment.MageCLI.Command.ExecuteManifestRelated() in C:\Users\jh\deployment-tools\src\clickonce\MageCLI\Command.cs:line 1439
3>     at Microsoft.Deployment.MageCLI.Command.Execute() in C:\Users\jh\deployment-tools\src\clickonce\MageCLI\Command.cs:line 1486
3>     at Microsoft.Deployment.MageCLI.Application.Main(String[] args) in C:\Users\jh\deployment-tools\src\clickonce\MageCLI\Application.cs:line 44
```

Problem solved by checking manifest.EntryPoint.TargetPath is not null

**Comment by NikolaMilosavljevic** [comment]
[Triage] @plutext can you provide a simple repro?

**Comment by janthomasQS** [comment]
I am looking at an ApplicationManifest that does not provide an entrypoint assembly but [customhostrequired ](https://learn.microsoft.com/en-us/visualstudio/deployment/entrypoint-element-clickonce-application?view=vs-2022#customhostrequired) instead. During Validation (which runs even after -Update) Manifest.Entrypoint is null which causes a the crash here: https://github.com/dotnet/deployment-tools/blob/main/src/clickonce/MageCLI/Command.cs#L1607
