### ISSUE TITLE
mage.exe partially enocdes manifest with SHA1

### ISSUE THREAD

**Issue by wegoodwin** [dotnet/deployment-tools#99]
I created a MS Word plugin with .net 4.8.  The customer has a slightly older version of MS word than what is on my development machine.  I get the following error when I try to run the plugin:

System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied.
at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
at System.Security.Cryptography.Xml.ManifestSignedXml.VerifyStrongNameSignature(XmlElement signatureNode)
at System.Security.Cryptography.Xml.ManifestSignedXml.VerifySignature(X509RevocationFlag revocationFlag, X509RevocationMode revocationMode) at System.Security.Cryptography.ManifestSignatureInformation.VerifySignature(ActivationContext application, ManifestKinds manifests, X509RevocationFlag revocationFlag, X509RevocationMode revocationMode)
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyCertificateSignature(ActivationContext context, OnlineOfflineState offlineState, String productName, DeploymentSignatureInformation& signatureInformation)
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

I tried a test plugin with the .net 4.0 runtime and it worked fine with no issues on my customers computer.  What I noticed was that the manifiests were signed with the SHA1 algorithm.  So I tried to use mage to re-sign my .net 4.8 deployment manifiest using SHA1 but it only converts part of the manifiest to SHA1.  I used the following command:

mage -Update MyApp.exe.manifest -CertHash MyHash -Algorithm sha1RSA

Did I do something incorrectly?

**Comment by NikolaMilosavljevic** [comment]
This seems to be an issue with .NET FX Mage tool, installed with Visual Studio or .NET FX SDK. The following page describes ways to submit feedback and open issues with these products: https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

**Comment by wegoodwin** [comment]
OK,  I submitted feedback with screenshots.  Do I need to close this issue?

**Comment by NikolaMilosavljevic** [comment]
Thanks @wegoodwin - closing the issue.
